# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.14.1
      hooks:
        - id: ruff
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
        - id: remove-tabs
          exclude: Makefile|docs/Makefile|docs/make.bat
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
    - repo: https://github.com/psf/black
      rev: 25.9.0
      hooks:
          - id: black
            exclude: versioneer.py|src/mda_tui/_version.py
