site_name: MDAnalysis TUI

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta

  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - content.code.annotate
    - content.code.copy

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
  search:
  autorefs:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_signature_annotations: false
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          show_source: false
          filters:
            - "!^_"
            - "^__init__$"
            - "!^can_replace$"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/p-j-smith/mda-tui/
      name: MDAnalysis TUI on Github
