name: docs
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4

      - name: Setup uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/.tox/**/*
            **/mkdocs.yml

      - name: Build HTML documentation with tox
        run: uv run mkdocs build

      - name: Publish docs if a release was made
        if: startsWith(github.ref, 'refs/tags/')
        run:  uv run mkdocs gh-deploy --force
