name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4

      - name: Setup uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/.tox/**/*
            **/.pre-commit-config.yaml

      - name: Test with tox
        run: uv run -- pre-commit run --all-files --color always --verbose
